### ISSUE TITLE
elevator issue

### ISSUE THREAD

**Issue by imcreativeaboutusernames** [Gann4/Thirdym#14]
when you jump off of the elevator theres a chance that you'll get both of your legs stuck on the ground
![what your doing step bot](https://user-images.githubusercontent.com/90115354/132110779-b731ac52-62b6-4b5e-b800-7239c37fedcd.png)

**Comment by Gann4** [comment]
This is more related to how physics interact with the enviroment and can't actually be fixed unless i add an option to change physics update rate in graphics or something.

Physics update rate has been decreased for the sake of not overwhelming the CPU with physics, 
The only fix for this is making the elevator completely solid instead of a plane-shaped platform.

Physics won't be fixed, but the elevator shape can be changed.
